version: "3"
services:
  web:
    build:
      context: ./apache-php
    ports:
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "./web-quest-back:/var/www/html"
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
    container_name: "web"
    platform: linux/x86_64
  db:
    platform: linux/x86_64
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql8.0"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: "phpmyamin"
    platform: linux/x86_64

